---
title: "Exam"
description: |
  What have you learned?
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

![Exams are learning instruments too... <br> <span>photo by <a href="https://unsplash.com/@anniespratt?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Annie Spratt</a> on <a href="https://unsplash.com/s/photos/test?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>](photos/annie-spratt-JexAuNCfefs-unsplash.jpg)

# Assessment

The assessment will take place 22.5.23, 14:15-15:45, and will consist of an in-person multiple-choice exam. 

The exam will be implemented on EvaExam and students will be asked to bring their own devices (BYOD principle) to complete the exam. 

We will have a practice trial with this system on 24.04.23. Those students who experience problems during the practice trial or prefer a paper-pencil version of the exam should make a direct request to the instructor at least 2 weeks before the final exam date (22.5.23). 

### Multiple-choice questions (correct combination of answers)

In this type of question, each answer can be either correct or incorrect; that is, 0, 1, 2, 3 or 4 answers can be correct (marked with a cross) or incorrect (no cross marked) respectively.
A choice must be made for each alternative answer.
If participants have checked or not checked the correct combination of answers, they receive full points (1). If only one check is not correctly placed, the participant will not receive any points (0) for the entire question.
The exam contains 25 questions. A maximum of 1 point can be earned per question (thus a maximum of 25 points can be earned for the exam). 