---
title: "EBDM"
description: |
  Welcome to the website for *Evidence-based decision making* FS22 ([11230-01](https://vorlesungsverzeichnis.unibas.ch/de/home?id=263293))
  
  Instructor: [Rui Mata](https://psychologie.unibas.ch/de/personen/rui-mata/about-me/), University of Basel
  
  **Last updated:** `r format(Sys.time(), "%a %b %d %X %Y")`
site: distill::distill_website
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Learn more about creating websites with Distill at:
# https://rstudio.github.io/distill/website.html

# Learn more about publishing to GitHub Pages at:
# https://rstudio.github.io/distill/publish_website.html#github-pages

```

![<span>Photo by <a href="https://unsplash.com/@carlevarino?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Cesar Carlevarino Aragon</a> on <a href="https://unsplash.com/s/photos/tools?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>](photos/cesar-carlevarino-aragon-NL_DF0Klepc-unsplash.jpg)

# Session information

Sessions take place Tuesdays, 16.15-17.45. Currently, the course is planned to be held in person but a change to an online format is possible depending on the current epidemiological situation.

::: l-body
| # | Date     | Topic                         | Slides |
|---| ---------|-------------------------------|--------|
| 1 | 22.02.2022 | [The Scientific Method(s)](session2.html) | [pdf](https://github.com/matarui/ebdm/raw/main/docs/presentations/EBDM_session1.pdf) |
| 2 | 01.03.2022 | [Algorithms](session3.html) | [pdf](https://github.com/matarui/ebdm/raw/main/docs/presentations/EBDM_session2.pdf) |
| 3 | 22.03.2022 | [Algorithms](session4.html) | [pdf](https://github.com/matarui/ebdm/raw/main/docs/presentations/EBDM_session3.pdf) |
| 4 | 29.03.2022 | [Consensus](session5.html) | [pdf](https://github.com/matarui/ebdm/raw/main/docs/presentations/EBDM_session4.pdf) |
| 5 | 05.04.2022 | [Consensus](session6.html) | [pdf](https://github.com/matarui/ebdm/raw/main/docs/presentations/EBDM_session5.pdf) |
| 6 | 12.04.2022 | [Counterfactuals](session7.html) | [pdf](https://github.com/matarui/ebdm/raw/main/docs/presentations/EBDM_session6.pdf) |
| 7 | 19.04.2022 | [Counterfactuals](session8.html) | [pdf](https://github.com/matarui/ebdm/raw/main/docs/presentations/EBDM_session7.pdf) |
| 8 | 26.04.2022 | [Synthesis](session9.html) | [pdf](https://github.com/matarui/ebdm/raw/main/docs/presentations/EBDM_session8.pdf) |
| 9 | 03.05.2022 | [Synthesis](session10.html) | [pdf](https://github.com/matarui/ebdm/raw/main/docs/presentations/EBDM_session9.pdf) |
|10 | 10.05.2022 | [Interventions](session11.html) | [pdf](index.html) |
|11 | 17.05.2022 | [Interventions](session12.html) | [pdf](index.html) |
|12 | 24.05.2022 | [Exam](exam.html) | |
:::


# What is this course about?

As the name implies, this course is about **evidence-based decision making**. The main premise of the course is that informed decisions require the use of evidence (i.e., data that has been processed in some way to generate knowledge or insight). 

The behavioral sciences, such as psychology and economics, have developed a number of concepts and techniques - a methodological toolbox - designed to transfrom data into evidence. This course aims to unpack some of these tools and showcase how they can be used in practice. 

The overarching theme of the course is that evidence-based decision making uses the tools of science to help us make better, informed decisions. This theme is reflected in the structure of the course: After the first two introductory sessions, the course is divided into modules covering 5 different scientific "methods", specifically, the benefits and limits of formalization (**Algorithms**), the discussion and amalgamation of diverse opinions (**Consensus**), the use of experiments and other methods to infer causality (**Counterfactuals**), the comprehensive and unbiased summary of multiple studies (**Synthesis**), and the establishment of guidelines and interventions based on the best possible evidence (**Interventions**). 

# What can you expect to learn?

The course will cover broad theoretical principles of evidence-based decision making. The principles will be illustrated with examples, that is, a few simple tutorials with example code in [R](https://www.r-project.org), and other recommended exercises designed to facilitate understanding of the underlying concepts.

### By completing the course you can expect to LEARN...

- central concepts in evidence-based decision making
- general principles of causal inference
- basic statistical concepts (e.g., aggregation, bias)
- guidelines for conducting and reporting scientific procedures  
- a taxonomy of behavioral interventions
- many practical and positive examples of evidence-based practices

### you will NOT, however, receive training in...

- mathematical analysis
- advanced programming skills 

# How should you use this website?

This website is designed to help course participants get an overview of the course and access most course materials (e.g., recommended background readings and videos, additional non-mandatory readings). A number of other resources, however, are available. An [FAQ](https://adam.unibas.ch/goto_adam_crs_1230794.html) forum is available on ADAM. If technically possible, the portions of the online sessions involving presentation by the instructor will be recorded and made available after each session on [SWITCHtube](https://tube.switch.ch/channels/0661df59). Information about the exam is available on the [Exam](exam.html) tab on this webpage.  

Course materials, such as readings or suggested preparation exercises, will be made available about one week before each session. The slides associated will be posted **after** each session but no video recording will be made available. 

<!-- # Video recordings and SWITCHtube -->

<!-- If technically possible, sessions involving presentation by the instructor will be recorded and made available after each session on [SWITCHtube](https://tube.switch.ch/channels/0661df59). All recordings will be deleted at the end of the semester. According to University of Basel's [regulations](https://www.unibas.ch/dam/jcr:9e482656-e333-42ec-bbd3-4639dedd3dc7/R_Ton-Bildaufnahmen_00.pdf) these **recordings** are for **personal use** only and should **not be further distributed** in any form.   -->
