---
title: "The Scientific Method(s)"
description: |
  Is there such a thing as THE scientific method?
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

![Sometimes it is good to start with a question or two... <span>Photo by <a href="https://unsplash.com/@jontyson?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Jon Tyson</a> on <a href="https://unsplash.com/s/photos/question?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>](photos/jon-tyson-hhq1Lxtuwd8-unsplash.jpg)

# What is the scientific method? And can we trust it?


What do **YOU** think? Do you trust science and scientists? If so, why? 

Please watch Naomi Oreskes' TED talk "Why we should trust scientists" (ca. 20 minutes) to learn more about the **scientific method(s)** and her thoughts on whether this ensures the trustworthiness of science and scientists. 

The video will serve as a starting point for a discussion on the methods of science in the *09.03.2021* session.  

<iframe width="560" height="515" src="https://www.youtube.com/embed/RxyQNEVOElU" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>


# What should we do to fix (psychological) science?

As discussed in the introductory session, the behavioral sciences, such as psychology, have been in the news in the past few years for wrong reasons - think **"replication crisis"**! But what should we be doing to change the status quo? Read the paper by **Munafò et al. (2017)** (ca. 60 minutes) to learn about some emerging solutions. The *09.03.2021* session will focus on some of these solutions.


### Recommended Reading

Munafò, M. R., Nosek, B. A., Bishop, D. V. M., Button, K. S., Chambers, C. D., Sert, du, N. P., et al. (2017). A manifesto for reproducible science. *Nature Human Behaviour, 1*, 1–9. [http://doi.org/10.1038/s41562-016-0021](https://github.com/matarui/ebdm/raw/main/docs/literature/Munafo_2017_NHB.pdf)

### Further Suggestions 

Are you interested in reading more about these topics? These books could be for you... 

Oreskes, N. (2019). *Why trust science?* Princeton: Oxford. Princeton University Press. [https://www.jstor.org/stable/j.ctvfjczxx](https://www.jstor.org/stable/j.ctvfjczxx)

Ritchie, S. (2020). *Science fictions: Exposing fraud, bias, negligence and hype in science*. London: Bodley Head. [https://www.sciencefictions.org](https://www.sciencefictions.org)

Rosling, H. (2018). *Factfulness. Ten reasons we're wrong about the world - and why things are better than you think*. Sceptre: London. [https://www.gapminder.org/factfulness-book/](https://www.gapminder.org/factfulness-book/)



